
export const allGIProducts = [
  {
    name: "Uttarakhand Tejpat",
    category: "Agricultural",
    region: "Chamoli, Uttarakhand",
    description: "Aromatic bay leaves with medicinal properties, organically grown in the Garhwal Himalayas",
    longDescription: "Uttarakhand Tejpat (Cinnamomum tamala) is a highly aromatic spice leaf grown in the pristine Himalayan environment. These leaves are used extensively in traditional cooking and Ayurvedic medicine, known for their digestive and anti-inflammatory benefits.",
    healthBenefits: [
      "Digestive aid and anti-inflammatory",
      "Traditional Ayurvedic medicine",
      "Rich in antioxidants",
      "Helps in respiratory health"
    ],
    culturalSignificance: "Tejpat leaves are an integral part of Garhwali cuisine and are used in traditional recipes. They are also used in religious ceremonies and are considered sacred in local culture.",
    images: ["/tejpatta.jpeg"],
    cloudinaryPublicIds: ["uttarakhand-heritage/products/tejpat-1"],
    rating: 4.7,
    reviewsCount: 95,
    culturalValue: "Traditional spice used in Garhwali cuisine and Ayurvedic medicine",
    available: true,
    giCertified: true,
    giRegistrationNumber: "520",
    giRegistrationDate: "31 May 2016",
    artisan: {
      id: "tejpat-artisan-1",
      name: "Tejpat Utpadak Samiti",
      village: "Chamoli",
      district: "Chamoli",
      experience: "Traditional",
      specialization: "Tejpat cultivation",
      contact: "tejpat@example.com",
      bio: "Traditional growers association preserving the authentic cultivation methods"
    },
    harvestSeason: "Year-round",
    shelfLife: "12 months",
    storageInstructions: "Store in airtight container away from moisture",
    tags: ["spice", "medicinal", "ayurvedic", "traditional"],
    keywords: ["tejpat", "bay leaves", "spice", "medicinal", "ayurvedic", "chamoli"]
  },
  {
    name: "Basmati Rice",
    category: "Agricultural",
    region: "Dehradun, Haridwar, Udham Singh Nagar",
    description: "Aromatic long-grain rice variety with distinctive fragrance and flavor",
    longDescription: "Uttarakhand Basmati Rice is a premium aromatic rice variety grown in the fertile plains of Dehradun, Haridwar, and Udham Singh Nagar districts. Known for its long grains, distinctive fragrance, and excellent cooking quality.",
    healthBenefits: [
      "Low glycemic index",
      "Rich in carbohydrates",
      "Gluten-free",
      "Easy to digest"
    ],
    culturalSignificance: "Basmati rice is a staple in Uttarakhand cuisine and is used in special occasions and festivals. It holds cultural importance in traditional ceremonies.",
    images: ["/basmati.jpeg"],
    cloudinaryPublicIds: ["uttarakhand-heritage/products/basmati-rice-1"],
    rating: 4.8,
    reviewsCount: 210,
    culturalValue: "Staple food used in festivals and special occasions",
    available: true,
    giCertified: true,
    giRegistrationNumber: "145",
    giRegistrationDate: "18 Aug 2016",
    artisan: {
      id: "basmati-artisan-1",
      name: "Basmati Growers Associations",
      village: "Dehradun",
      district: "Dehradun",
      experience: "Traditional",
      specialization: "Basmati rice cultivation",
      contact: "basmati@example.com",
      bio: "Association of traditional basmati rice growers"
    },
    harvestSeason: "October - November",
    shelfLife: "18 months",
    storageInstructions: "Store in cool, dry place",
    tags: ["rice", "staple", "aromatic", "traditional"],
    keywords: ["basmati", "rice", "aromatic", "staple", "dehradun"]
  },
  {
    name: "Aipan Art",
    category: "Handicraft",
    region: "Kumaon region",
    description: "Traditional ritualistic art on walls and floors with geometric patterns",
    longDescription: "Aipan is a traditional folk art of Kumaon region, characterized by intricate geometric patterns painted with rice paste on red ochre background. This sacred art form is practiced during festivals, ceremonies, and auspicious occasions.",
    healthBenefits: ["Therapeutic art practice", "Stress relief through meditation", "Enhances creativity and focus"],
    culturalSignificance: "Sacred art form used in festivals and ceremonies, believed to bring prosperity and ward off evil spirits. Traditionally painted by women during Diwali, weddings, and other auspicious occasions.",
    images: ["/aipan-art-traditional-patterns-geometric.jpg"],
    cloudinaryPublicIds: ["uttarakhand-heritage/products/aipan-art-1"],
    rating: 4.9,
    reviewsCount: 89,
    culturalValue: "Sacred art form used in festivals and ceremonies",
    available: true,
    giCertified: true,
    giRegistrationNumber: "837",
    giRegistrationDate: "2021",
    artisan: {
      id: "meera-bisht-id",
      name: "Kumaoni women artisans",
      village: "Almora",
      district: "Almora",
      experience: "30+ years",
      specialization: "Aipan Art",
      contact: "aipan@example.com",
      bio: "Master artists preserving traditional Aipan art form"
    },
    dimensions: '12" x 16"',
    materials: "Rice paste, natural ochre, handmade paper",
    careInstructions: "Keep away from moisture and direct sunlight",
    tags: ["art", "traditional", "cultural", "sacred"],
    keywords: ["aipan", "art", "geometric", "sacred", "spiritual", "traditional", "patterns"]
  },
  {
    name: "Munsiyari White Kidney Beans (Rajma)",
    category: "Agricultural",
    region: "Pithoragarh district",
    description: "High altitude white kidney beans grown in organic conditions",
    longDescription: "Munsiyari White Kidney Beans are a premium variety grown in the high-altitude regions of Pithoragarh district. These beans are cultivated using traditional organic farming methods and are known for their exceptional taste and nutritional value.",
    healthBenefits: [
      "Rich in iron & calcium",
      "High protein content (22g per 100g)",
      "Diabetic-friendly with low glycemic index",
      "High fiber content aids digestion",
      "Rich in folate and magnesium"
    ],
    culturalSignificance: "Traditional staple food of Kumaon region, often prepared during festivals and special occasions. The beans are considered sacred and are offered in local temples during harvest festivals.",
    images: ["/munsiyari-rajma-kidney-beans-red.jpg"],
    cloudinaryPublicIds: ["uttarakhand-heritage/products/munsiyari-rajma-1"],
    rating: 4.8,
    reviewsCount: 124,
    culturalValue: "Traditional staple food of Kumaon region",
    available: true,
    giCertified: true,
    giRegistrationNumber: "854",
    giRegistrationDate: "2023",
    artisan: {
      id: "rajesh-negi-id",
      name: "Local farmers of Munsiyari",
      village: "Munsiyari",
      district: "Pithoragarh",
      experience: "25+ years",
      specialization: "Organic farming",
      contact: "rajma@example.com",
      bio: "Traditional farmers preserving indigenous bean varieties"
    },
    nutritionalInfo: {
      protein: "22g",
      carbs: "60g",
      fiber: "15g",
      iron: "8.2mg",
      calcium: "143mg",
      calories: "333 kcal"
    },
    harvestSeason: "September - October",
    shelfLife: "12 months",
    storageInstructions: "Store in a cool, dry place away from direct sunlight",
    cookingInstructions: [
      "Soak beans overnight in water",
      "Pressure cook for 15-20 minutes",
      "Season with traditional spices",
      "Best served with rice or roti"
    ],
    tags: ["organic", "traditional", "healthy", "protein-rich"],
    keywords: ["rajma", "kidney beans", "protein", "organic", "munsiyari", "health", "traditional"]
  },
  {
    name: "Ringal Craft",
    category: "Handicraft",
    region: "Almora, Bageshwar, Chamoli",
    description: "Crafts made from Himalayan bamboo with traditional weaving techniques",
    longDescription: "Ringal Craft involves creating beautiful and functional items from Ringaal bamboo, a species native to the Himalayan region. This eco-friendly craft produces baskets, containers, and decorative items using traditional weaving patterns passed down through generations.",
    healthBenefits: ["Eco-friendly and sustainable", "Promotes traditional skills", "Therapeutic crafting activity"],
    culturalSignificance: "Traditional craft passed down through generations, representing the sustainable lifestyle of mountain communities. Ringal products are used in daily life and are also part of cultural ceremonies.",
    images: ["/ringaal-bamboo-craft-basket-traditional.jpg"],
    cloudinaryPublicIds: ["uttarakhand-heritage/products/ringal-craft-1"],
    rating: 4.7,
    reviewsCount: 112,
    culturalValue: "Traditional craft representing sustainable mountain lifestyle",
    available: true,
    giCertified: true,
    giRegistrationNumber: "505",
    giRegistrationDate: "2015",
    artisan: {
      id: "ringal-artisan-1",
      name: "Ringal craft artisans",
      village: "Almora",
      district: "Almora",
      experience: "Traditional",
      specialization: "Ringal bamboo craft",
      contact: "ringal@example.com",
      bio: "Traditional artisans preserving Ringal bamboo craft"
    },
    materials: "Ringaal bamboo, natural fibers",
    careInstructions: "Clean with dry cloth, avoid water exposure",
    tags: ["bamboo", "handicraft", "eco-friendly", "traditional"],
    keywords: ["ringal", "bamboo", "craft", "basket", "traditional", "eco-friendly"]
  },
  {
    name: "Thulma Blanket",
    category: "Textile",
    region: "Chamoli, Uttarkashi",
    description: "Handwoven woolen blanket with traditional patterns",
    longDescription: "Thulma Blanket is a traditional handwoven woolen blanket made by skilled Bhotia weavers. These blankets are known for their warmth, durability, and intricate traditional patterns that reflect the cultural heritage of the Garhwal region.",
    healthBenefits: ["Natural insulation", "Hypoallergenic", "Breathable fabric"],
    culturalSignificance: "Traditional winter wear essential in mountain communities. These blankets are part of dowry and are used in cultural ceremonies. They represent the weaving expertise of Bhotia communities.",
    images: ["/traditional-woolen-caps-coats-uttarakhand-winter-w.jpg"],
    cloudinaryPublicIds: ["uttarakhand-heritage/products/thulma-blanket-1"],
    rating: 4.6,
    reviewsCount: 78,
    culturalValue: "Traditional winter wear representing Bhotia weaving heritage",
    available: true,
    giCertified: true,
    giRegistrationNumber: "836",
    giRegistrationDate: "2021",
    artisan: {
      id: "thulma-artisan-1",
      name: "Bhotia weavers",
      village: "Chamoli",
      district: "Chamoli",
      experience: "Traditional",
      specialization: "Woolen blanket weaving",
      contact: "thulma@example.com",
      bio: "Traditional Bhotia weavers preserving ancient weaving techniques"
    },
    materials: "Sheep wool, natural dyes",
    careInstructions: "Dry clean only, store in dry place",
    tags: ["wool", "textile", "blanket", "traditional", "handwoven"],
    keywords: ["thulma", "blanket", "wool", "handwoven", "bhotia", "winter"]
  },
  {
    name: "Bhotiya Dann (Rug)",
    category: "Textile",
    region: "Chamoli, Pithoragarh",
    description: "Handmade wool rug with intricate traditional patterns",
    longDescription: "Bhotiya Dann is a traditional handmade wool rug created by Bhotiya tribal artisans. These rugs feature intricate patterns and designs that are unique to the Pithoragarh and Chamoli regions, representing the cultural identity of the Bhotiya community.",
    healthBenefits: ["Natural fiber", "Durable", "Eco-friendly"],
    culturalSignificance: "Represents the unique cultural identity and weaving expertise of the Bhotiya tribal community. These rugs are used in homes and are also part of cultural ceremonies.",
    images: ["/bhotiya.jpeg"],
    cloudinaryPublicIds: ["uttarakhand-heritage/products/bhotiya-dann-1"],
    rating: 4.7,
    reviewsCount: 65,
    culturalValue: "Traditional rug representing Bhotiya tribal heritage",
    available: true,
    giCertified: true,
    giRegistrationNumber: "835",
    giRegistrationDate: "2021",
    artisan: {
      id: "bhotiya-artisan-1",
      name: "Bhotiya tribal artisans",
      village: "Pithoragarh",
      district: "Pithoragarh",
      experience: "Traditional",
      specialization: "Wool rug making",
      contact: "bhotiya@example.com",
      bio: "Bhotiya tribal artisans preserving traditional rug making"
    },
    materials: "Sheep wool, natural dyes",
    careInstructions: "Vacuum regularly, professional cleaning recommended",
    tags: ["rug", "wool", "textile", "tribal", "traditional"],
    keywords: ["bhotiya", "dann", "rug", "wool", "tribal", "handmade"]
  },
  {
    name: "Kumaon Chiura (Chyura) Oil",
    category: "Agricultural",
    region: "Kumaon region",
    description: "Traditional oil from Diploknema butyracea with medicinal properties",
    longDescription: "Kumaon Chiura Oil is extracted from the seeds of Diploknema butyracea, a tree native to the Kumaon region. This traditional oil has been used for centuries in cooking and Ayurvedic medicine, known for its health benefits.",
    healthBenefits: [
      "Rich in healthy fats",
      "Traditional Ayurvedic medicine",
      "Skin care benefits",
      "Anti-inflammatory properties"
    ],
    culturalSignificance: "Traditional oil used in Kumaoni cuisine and Ayurvedic practices. It holds cultural importance in local food traditions and medicinal practices.",
    images: ["/chiura.jpeg"],
    cloudinaryPublicIds: ["uttarakhand-heritage/products/chiura-oil-1"],
    rating: 4.5,
    reviewsCount: 42,
    culturalValue: "Traditional oil used in Kumaoni cuisine and Ayurveda",
    available: true,
    giCertified: true,
    giRegistrationNumber: "832",
    giRegistrationDate: "2021",
    artisan: {
      id: "chiura-artisan-1",
      name: "Local oil producers",
      village: "Kumaon",
      district: "Almora",
      experience: "Traditional",
      specialization: "Chiura oil extraction",
      contact: "chiura@example.com",
      bio: "Traditional oil producers preserving ancient extraction methods"
    },
    harvestSeason: "Year-round",
    shelfLife: "24 months",
    storageInstructions: "Store in cool, dark place",
    tags: ["oil", "ayurvedic", "medicinal", "traditional"],
    keywords: ["chiura", "chyura", "oil", "ayurvedic", "kumaon", "medicinal"]
  },
  {
    name: "Copper Products (Tamta Craft)",
    category: "Handicraft",
    region: "Almora district",
    description: "Handmade copper utensils and décor items with traditional designs",
    longDescription: "Tamta Craft involves creating beautiful copper utensils and decorative items using traditional techniques. These products are known for their durability, aesthetic appeal, and cultural significance in Uttarakhand households.",
    healthBenefits: ["Copper has antimicrobial properties", "Traditional cooking benefits", "Durable and long-lasting"],
    culturalSignificance: "Copper utensils are an integral part of traditional Uttarakhand households. They are used in religious ceremonies and are considered auspicious. The craft represents the Tamta community's expertise.",
    images: ["/copper.jpeg"],
    cloudinaryPublicIds: ["uttarakhand-heritage/products/copper-tamta-1"],
    rating: 4.6,
    reviewsCount: 88,
    culturalValue: "Traditional copper craft representing Tamta community heritage",
    available: true,
    giCertified: true,
    giRegistrationNumber: "834",
    giRegistrationDate: "2021",
    artisan: {
      id: "tamta-artisan-1",
      name: "Tamta community",
      village: "Almora",
      district: "Almora",
      experience: "Traditional",
      specialization: "Copper craft",
      contact: "tamta@example.com",
      bio: "Tamta community artisans preserving traditional copper craft"
    },
    materials: "Pure copper, traditional tools",
    careInstructions: "Clean with lemon and salt, polish regularly",
    tags: ["copper", "handicraft", "utensils", "traditional"],
    keywords: ["tamta", "copper", "utensils", "craft", "traditional", "almora"]
  },
  {
    name: "Chaulai (Ramdana)",
    category: "Agricultural",
    region: "Almora, Chamoli",
    description: "Protein-rich amaranth grain with high nutritional value",
    longDescription: "Chaulai, also known as Ramdana, is a highly nutritious amaranth grain grown in the hilly regions of Almora and Chamoli. This traditional grain is rich in protein and has been a staple in local diets for centuries.",
    healthBenefits: [
      "High protein content (14-15%)",
      "Rich in iron and calcium",
      "Gluten-free",
      "High fiber content",
      "Contains essential amino acids"
    ],
    culturalSignificance: "Traditional grain used in local cuisine, especially during festivals. It's considered nutritious and is part of traditional food practices in the region.",
    images: ["/chaulai.jpeg"],
    cloudinaryPublicIds: ["uttarakhand-heritage/products/chaulai-1"],
    rating: 4.7,
    reviewsCount: 56,
    culturalValue: "Traditional nutritious grain used in local cuisine",
    available: true,
    giCertified: true,
    giRegistrationNumber: "853",
    giRegistrationDate: "2023",
    artisan: {
      id: "chaulai-artisan-1",
      name: "Farmer cooperatives",
      village: "Almora",
      district: "Almora",
      experience: "Traditional",
      specialization: "Amaranth cultivation",
      contact: "chaulai@example.com",
      bio: "Traditional farmers growing amaranth grain"
    },
    nutritionalInfo: {
      protein: "14g",
      carbs: "65g",
      fiber: "7g",
      iron: "7.6mg",
      calcium: "159mg",
      calories: "371 kcal"
    },
    harvestSeason: "October - November",
    shelfLife: "18 months",
    storageInstructions: "Store in airtight container",
    tags: ["grain", "protein-rich", "gluten-free", "traditional"],
    keywords: ["chaulai", "ramdana", "amaranth", "grain", "protein", "traditional"]
  },
  {
    name: "Jhangora (Barnyard Millet)",
    category: "Agricultural",
    region: "Bageshwar, Almora",
    description: "Millet grown in hilly terrain with high nutritional value",
    longDescription: "Jhangora, or Barnyard Millet, is a traditional millet variety grown in the hilly terrain of Bageshwar and Almora districts. This nutritious grain is known for its health benefits and is a staple in traditional diets.",
    healthBenefits: [
      "High fiber content",
      "Low glycemic index",
      "Rich in B vitamins",
      "Gluten-free",
      "Good source of minerals"
    ],
    culturalSignificance: "Traditional millet used in local cuisine, especially in rural areas. It's part of the traditional food culture of the region.",
    images: ["/jhangora.jpeg"],
    cloudinaryPublicIds: ["uttarakhand-heritage/products/jhangora-1"],
    rating: 4.6,
    reviewsCount: 48,
    culturalValue: "Traditional millet representing local food culture",
    available: true,
    giCertified: true,
    giRegistrationNumber: "851",
    giRegistrationDate: "2023",
    artisan: {
      id: "jhangora-artisan-1",
      name: "Local millet growers",
      village: "Bageshwar",
      district: "Bageshwar",
      experience: "Traditional",
      specialization: "Millet cultivation",
      contact: "jhangora@example.com",
      bio: "Traditional millet growers preserving indigenous varieties"
    },
    nutritionalInfo: {
      protein: "11g",
      carbs: "65g",
      fiber: "10g",
      iron: "5mg",
      calcium: "20mg",
      calories: "300 kcal"
    },
    harvestSeason: "September - October",
    shelfLife: "12 months",
    storageInstructions: "Store in cool, dry place",
    tags: ["millet", "grain", "gluten-free", "traditional"],
    keywords: ["jhangora", "barnyard millet", "millet", "grain", "traditional", "bageshwar"]
  },
  {
    name: "Uttarakhand Lal Chawal (Red Rice)",
    category: "Agricultural",
    region: "Uttarkashi",
    description: "Aromatic red rice variety with distinctive color and flavor",
    longDescription: "Uttarakhand Lal Chawal is a unique aromatic red rice variety grown in the Uttarkashi district. This rice is known for its distinctive red color, nutty flavor, and high nutritional value.",
    healthBenefits: [
      "Rich in antioxidants",
      "High fiber content",
      "Low glycemic index",
      "Contains iron and zinc"
    ],
    culturalSignificance: "Traditional rice variety used in local cuisine and special occasions. It holds cultural importance in the region's food traditions.",
    images: ["/lal-chawal.jpeg"],
    cloudinaryPublicIds: ["uttarakhand-heritage/products/lal-chawal-1"],
    rating: 4.7,
    reviewsCount: 72,
    culturalValue: "Traditional red rice variety with cultural significance",
    available: true,
    giCertified: true,
    giRegistrationNumber: "852",
    giRegistrationDate: "2023",
    artisan: {
      id: "lal-chawal-artisan-1",
      name: "Bhagirathi Annapurna Swayat Sahakarita",
      village: "Uttarkashi",
      district: "Uttarkashi",
      experience: "Traditional",
      specialization: "Red rice cultivation",
      contact: "lalchawal@example.com",
      bio: "Cooperative of traditional red rice growers"
    },
    harvestSeason: "October - November",
    shelfLife: "18 months",
    storageInstructions: "Store in cool, dry place",
    tags: ["rice", "red rice", "aromatic", "traditional"],
    keywords: ["lal chawal", "red rice", "uttarkashi", "aromatic", "traditional"]
  },
  {
    name: "Mandua (Finger Millet)",
    category: "Agricultural",
    region: "Pauri Garhwal",
    description: "Nutritious finger millet with high calcium content",
    longDescription: "Mandua, or Finger Millet, is a highly nutritious millet variety grown in Pauri Garhwal. This grain is known for its high calcium content and is a staple in traditional diets.",
    healthBenefits: [
      "High calcium content",
      "Rich in iron",
      "High fiber",
      "Gluten-free",
      "Good for bone health"
    ],
    culturalSignificance: "Traditional millet used in local cuisine, especially in rural Garhwal. It's an important part of the traditional food culture.",
    images: ["/mandua.jpeg"],
    cloudinaryPublicIds: ["uttarakhand-heritage/products/mandua-1"],
    rating: 4.6,
    reviewsCount: 64,
    culturalValue: "Traditional finger millet representing Garhwal food culture",
    available: true,
    giCertified: true,
    giRegistrationNumber: "850",
    giRegistrationDate: "2023",
    artisan: {
      id: "mandua-artisan-1",
      name: "Farmer cooperatives",
      village: "Pauri",
      district: "Pauri Garhwal",
      experience: "Traditional",
      specialization: "Finger millet cultivation",
      contact: "mandua@example.com",
      bio: "Traditional farmers growing finger millet"
    },
    nutritionalInfo: {
      protein: "7g",
      carbs: "72g",
      fiber: "11g",
      iron: "3.9mg",
      calcium: "344mg",
      calories: "328 kcal"
    },
    harvestSeason: "September - October",
    shelfLife: "12 months",
    storageInstructions: "Store in airtight container",
    tags: ["millet", "finger millet", "calcium-rich", "traditional"],
    keywords: ["mandua", "finger millet", "ragi", "millet", "traditional", "pauri"]
  },
  {
    name: "Almora Lakhori Mirchi",
    category: "Agricultural",
    region: "Almora",
    description: "Local red chili variety with distinctive flavor",
    longDescription: "Almora Lakhori Mirchi is a unique local red chili variety grown in the Almora district. These chilies are known for their distinctive flavor and moderate heat, making them perfect for traditional Garhwali and Kumaoni cuisine.",
    healthBenefits: [
      "Rich in Vitamin C",
      "Contains capsaicin",
      "Metabolism booster",
      "Antioxidant properties"
    ],
    culturalSignificance: "Essential spice in local cuisine, used in traditional recipes. It's an integral part of the region's culinary heritage.",
    images: ["/lakhori.jpeg"],
    cloudinaryPublicIds: ["uttarakhand-heritage/products/lakhori-mirchi-1"],
    rating: 4.5,
    reviewsCount: 38,
    culturalValue: "Traditional spice essential to local cuisine",
    available: true,
    giCertified: true,
    giRegistrationNumber: "855",
    giRegistrationDate: "2023",
    artisan: {
      id: "mirchi-artisan-1",
      name: "Chokot Patti Farmers Producer Co.",
      village: "Almora",
      district: "Almora",
      experience: "Traditional",
      specialization: "Chili cultivation",
      contact: "mirchi@example.com",
      bio: "Farmer cooperative growing traditional chili varieties"
    },
    harvestSeason: "Year-round",
    shelfLife: "24 months",
    storageInstructions: "Store in airtight container away from moisture",
    tags: ["chili", "spice", "traditional", "culinary"],
    keywords: ["lakhori", "mirchi", "chili", "spice", "almora", "traditional"]
  },
  {
    name: "Uttarakhand Berinag Tea",
    category: "Agricultural",
    region: "Pithoragarh (Berinag)",
    description: "Tea grown in high altitude with unique flavor profile",
    longDescription: "Uttarakhand Berinag Tea is a premium tea variety grown in the high-altitude region of Berinag in Pithoragarh district. The unique climatic conditions give this tea its distinctive flavor and aroma.",
    healthBenefits: [
      "Rich in antioxidants",
      "Boosts metabolism",
      "Improves mental alertness",
      "Heart health benefits"
    ],
    culturalSignificance: "Tea is an important part of local culture and hospitality. Berinag tea represents the region's tea-growing heritage.",
    images: ["/tea.jpeg"],
    cloudinaryPublicIds: ["uttarakhand-heritage/products/berinag-tea-1"],
    rating: 4.7,
    reviewsCount: 91,
    culturalValue: "High-altitude tea representing regional tea heritage",
    available: true,
    giCertified: true,
    giRegistrationNumber: "856",
    giRegistrationDate: "2023",
    artisan: {
      id: "tea-artisan-1",
      name: "Berinag Tea Farmers",
      village: "Berinag",
      district: "Pithoragarh",
      experience: "Traditional",
      specialization: "Tea cultivation",
      contact: "berinagtea@example.com",
      bio: "Traditional tea growers in high-altitude regions"
    },
    harvestSeason: "March - November",
    shelfLife: "36 months",
    storageInstructions: "Store in airtight container away from light and moisture",
    tags: ["tea", "beverage", "high-altitude", "traditional"],
    keywords: ["berinag", "tea", "pithoragarh", "high-altitude", "traditional"]
  },
  {
    name: "Ramnagar Nainital Litchi",
    category: "Agricultural",
    region: "Ramnagar, Nainital",
    description: "Sweet and juicy litchi variety with exceptional taste",
    longDescription: "Ramnagar Nainital Litchi is a premium variety of litchi grown in the Ramnagar and Nainital regions. These litchis are known for their exceptional sweetness, juiciness, and distinctive flavor.",
    healthBenefits: [
      "Rich in Vitamin C",
      "High water content",
      "Antioxidant properties",
      "Boosts immunity"
    ],
    culturalSignificance: "Litchi is a seasonal delicacy in the region and is part of local food culture. It's enjoyed during the summer season.",
    images: ["/litchi.jpeg"],
    cloudinaryPublicIds: ["uttarakhand-heritage/products/litchi-1"],
    rating: 4.8,
    reviewsCount: 105,
    culturalValue: "Seasonal fruit representing regional fruit heritage",
    available: true,
    giCertified: true,
    giRegistrationNumber: "857",
    giRegistrationDate: "2023",
    artisan: {
      id: "litchi-artisan-1",
      name: "Fruit growers of Nainital",
      village: "Ramnagar",
      district: "Nainital",
      experience: "Traditional",
      specialization: "Litchi cultivation",
      contact: "litchi@example.com",
      bio: "Traditional fruit growers specializing in litchi"
    },
    harvestSeason: "May - June",
    shelfLife: "5-7 days",
    storageInstructions: "Store in cool place, consume fresh",
    tags: ["fruit", "litchi", "seasonal", "traditional"],
    keywords: ["litchi", "ramnagar", "nainital", "fruit", "seasonal"]
  },
  {
    name: "Ramgarh Nainital Aadu (Peach)",
    category: "Agricultural",
    region: "Ramgarh, Nainital",
    description: "Peach variety known for aroma and flavor",
    longDescription: "Ramgarh Nainital Aadu is a premium peach variety grown in the Ramgarh region of Nainital district. These peaches are known for their exceptional aroma, sweet flavor, and juicy texture.",
    healthBenefits: [
      "Rich in Vitamin C",
      "High fiber content",
      "Antioxidant properties",
      "Supports skin health"
    ],
    culturalSignificance: "Peach is a seasonal fruit enjoyed in the region. It's part of the local fruit culture and is used in traditional recipes.",
    images: ["/aadu.jpg"],
    cloudinaryPublicIds: ["uttarakhand-heritage/products/aadu-1"],
    rating: 4.6,
    reviewsCount: 58,
    culturalValue: "Seasonal peach variety representing regional fruit heritage",
    available: true,
    giCertified: true,
    giRegistrationNumber: "858",
    giRegistrationDate: "2023",
    artisan: {
      id: "aadu-artisan-1",
      name: "Local peach growers",
      village: "Ramgarh",
      district: "Nainital",
      experience: "Traditional",
      specialization: "Peach cultivation",
      contact: "aadu@example.com",
      bio: "Traditional peach growers in Ramgarh region"
    },
    harvestSeason: "June - July",
    shelfLife: "7-10 days",
    storageInstructions: "Store in cool place, handle gently",
    tags: ["fruit", "peach", "seasonal", "traditional"],
    keywords: ["aadu", "peach", "ramgarh", "nainital", "fruit", "seasonal"]
  },
  {
    name: "Uttarakhand Malta Fruit",
    category: "Agricultural",
    region: "Garhwal region",
    description: "Citrus fruit with rich flavor and high Vitamin C",
    longDescription: "Uttarakhand Malta is a citrus fruit variety grown in the Garhwal region. This fruit is known for its rich flavor, high Vitamin C content, and distinctive taste that reflects the region's unique growing conditions.",
    healthBenefits: [
      "Very high Vitamin C content",
      "Boosts immunity",
      "Antioxidant properties",
      "Supports skin health"
    ],
    culturalSignificance: "Malta is an important citrus fruit in the region and is used in local cuisine and traditional recipes. It's part of the region's fruit heritage.",
    images: ["/malta.jpg"],
    cloudinaryPublicIds: ["uttarakhand-heritage/products/malta-1"],
    rating: 4.5,
    reviewsCount: 47,
    culturalValue: "Citrus fruit representing Garhwal fruit heritage",
    available: true,
    giCertified: true,
    giRegistrationNumber: "859",
    giRegistrationDate: "2023",
    artisan: {
      id: "malta-artisan-1",
      name: "Malta producers",
      village: "Garhwal",
      district: "Garhwal",
      experience: "Traditional",
      specialization: "Citrus fruit cultivation",
      contact: "malta@example.com",
      bio: "Traditional citrus fruit growers in Garhwal"
    },
    harvestSeason: "December - February",
    shelfLife: "2-3 weeks",
    storageInstructions: "Store in cool, dry place",
    tags: ["fruit", "citrus", "malta", "traditional"],
    keywords: ["malta", "citrus", "fruit", "garhwal", "vitamin c"]
  },
  {
    name: "Uttarakhand Pahari Toor Dal",
    category: "Agricultural",
    region: "Chamoli, Tehri",
    description: "Pigeon pea grown in hilly areas with traditional methods",
    longDescription: "Uttarakhand Pahari Toor Dal is a variety of pigeon pea grown in the hilly areas of Chamoli and Tehri districts. This dal is cultivated using traditional methods and is known for its taste and nutritional value.",
    healthBenefits: [
      "High protein content",
      "Rich in fiber",
      "Good source of iron",
      "Gluten-free"
    ],
    culturalSignificance: "Toor dal is a staple in local cuisine and is used in traditional recipes. It's an important part of the region's food culture.",
    images: ["/toor-daal.jpg"],
    cloudinaryPublicIds: ["uttarakhand-heritage/products/toor-dal-1"],
    rating: 4.6,
    reviewsCount: 73,
    culturalValue: "Traditional dal representing regional food culture",
    available: true,
    giCertified: true,
    giRegistrationNumber: "867",
    giRegistrationDate: "2023",
    artisan: {
      id: "toor-dal-artisan-1",
      name: "SEWA Koshish Kisaan Sahakarita",
      village: "Chamoli",
      district: "Chamoli",
      experience: "Traditional",
      specialization: "Pigeon pea cultivation",
      contact: "toordal@example.com",
      bio: "Farmer cooperative growing traditional pigeon pea"
    },
    nutritionalInfo: {
      protein: "22g",
      carbs: "63g",
      fiber: "15g",
      iron: "5mg",
      calcium: "130mg",
      calories: "343 kcal"
    },
    harvestSeason: "October - November",
    shelfLife: "12 months",
    storageInstructions: "Store in cool, dry place",
    tags: ["dal", "pigeon pea", "protein-rich", "traditional"],
    keywords: ["toor dal", "pigeon pea", "dal", "traditional", "chamoli"]
  },
  {
    name: "Uttarakhand Gahat (Horse Gram)",
    category: "Agricultural",
    region: "Kumaon & Garhwal",
    description: "Protein-rich lentil with high nutritional value",
    longDescription: "Uttarakhand Gahat, or Horse Gram, is a highly nutritious lentil variety grown in both Kumaon and Garhwal regions. This protein-rich legume has been a traditional food source in the region for centuries.",
    healthBenefits: [
      "Very high protein content",
      "Rich in iron",
      "High fiber",
      "Good for bone health",
      "Supports weight management"
    ],
    culturalSignificance: "Gahat is a traditional lentil used in local cuisine, especially in rural areas. It's an important part of the region's food heritage.",
    images: ["/gahat.jpeg"],
    cloudinaryPublicIds: ["uttarakhand-heritage/products/gahat-1"],
    rating: 4.7,
    reviewsCount: 81,
    culturalValue: "Traditional protein-rich lentil representing regional food heritage",
    available: true,
    giCertified: true,
    giRegistrationNumber: "860",
    giRegistrationDate: "2023",
    artisan: {
      id: "gahat-artisan-1",
      name: "Farmer groups",
      village: "Kumaon",
      district: "Almora",
      experience: "Traditional",
      specialization: "Horse gram cultivation",
      contact: "gahat@example.com",
      bio: "Traditional farmers growing horse gram"
    },
    nutritionalInfo: {
      protein: "22g",
      carbs: "57g",
      fiber: "5g",
      iron: "7mg",
      calcium: "287mg",
      calories: "321 kcal"
    },
    harvestSeason: "October - November",
    shelfLife: "12 months",
    storageInstructions: "Store in airtight container",
    tags: ["lentil", "horse gram", "protein-rich", "traditional"],
    keywords: ["gahat", "horse gram", "lentil", "protein", "traditional"]
  },
  {
    name: "Uttarakhand Kala Bhat",
    category: "Agricultural",
    region: "Kumaon",
    description: "Black soybean variety with high protein content",
    longDescription: "Uttarakhand Kala Bhat is a black soybean variety grown in the Kumaon region. These soybeans are known for their high protein content and are used in traditional recipes.",
    healthBenefits: [
      "Very high protein content",
      "Rich in isoflavones",
      "Good source of iron",
      "Supports heart health"
    ],
    culturalSignificance: "Black soybeans are used in traditional recipes and are part of the local food culture. They're valued for their nutritional properties.",
    images: ["/kala-bhat.jpeg"],
    cloudinaryPublicIds: ["uttarakhand-heritage/products/kala-bhat-1"],
    rating: 4.6,
    reviewsCount: 52,
    culturalValue: "Traditional black soybean representing regional food heritage",
    available: true,
    giCertified: true,
    giRegistrationNumber: "861",
    giRegistrationDate: "2023",
    artisan: {
      id: "kala-bhat-artisan-1",
      name: "Local farmer cooperative",
      village: "Kumaon",
      district: "Almora",
      experience: "Traditional",
      specialization: "Black soybean cultivation",
      contact: "kalabhat@example.com",
      bio: "Traditional farmers growing black soybeans"
    },
    nutritionalInfo: {
      protein: "36g",
      carbs: "30g",
      fiber: "9g",
      iron: "15.7mg",
      calcium: "277mg",
      calories: "446 kcal"
    },
    harvestSeason: "October - November",
    shelfLife: "12 months",
    storageInstructions: "Store in cool, dry place",
    tags: ["soybean", "black soybean", "protein-rich", "traditional"],
    keywords: ["kala bhat", "black soybean", "soybean", "protein", "traditional"]
  },
  {
    name: "Uttarakhand Bichhu Buti (Nettle) Fabric",
    category: "Textile",
    region: "Chamoli, Pithoragarh",
    description: "Handwoven nettle fabric with traditional techniques",
    longDescription: "Uttarakhand Bichhu Buti Fabric is made from nettle fibers using traditional handweaving techniques. This eco-friendly fabric is known for its durability and unique texture, representing the sustainable textile heritage of the region.",
    healthBenefits: [
      "Natural fiber",
      "Eco-friendly",
      "Breathable",
      "Hypoallergenic"
    ],
    culturalSignificance: "Nettle fabric represents the traditional textile heritage of the region. It's used in making traditional garments and is part of the sustainable textile practices.",
    images: ["/bichhu-buti.jpeg"],
    cloudinaryPublicIds: ["uttarakhand-heritage/products/bichhu-buti-1"],
    rating: 4.5,
    reviewsCount: 34,
    culturalValue: "Traditional nettle fabric representing sustainable textile heritage",
    available: true,
    giCertified: true,
    giRegistrationNumber: "862",
    giRegistrationDate: "2023",
    artisan: {
      id: "bichhu-artisan-1",
      name: "Weaver communities",
      village: "Chamoli",
      district: "Chamoli",
      experience: "Traditional",
      specialization: "Nettle fabric weaving",
      contact: "bichhu@example.com",
      bio: "Traditional weavers creating nettle fabric"
    },
    materials: "Nettle fibers, natural dyes",
    careInstructions: "Hand wash with mild detergent",
    tags: ["fabric", "nettle", "textile", "eco-friendly", "traditional"],
    keywords: ["bichhu buti", "nettle", "fabric", "textile", "handwoven", "eco-friendly"]
  },
  {
    name: "Rangwali Pichhoda (Kumaon)",
    category: "Textile",
    region: "Kumaon region",
    description: "Traditional women's shawl with colorful patterns",
    longDescription: "Rangwali Pichhoda is a traditional women's shawl from the Kumaon region, known for its colorful patterns and intricate designs. These shawls are handwoven using traditional techniques and represent the textile heritage of Kumaon.",
    healthBenefits: ["Natural fiber", "Warm and comfortable", "Breathable"],
    culturalSignificance: "Traditional shawl worn by women in Kumaon, especially during festivals and special occasions. It represents the cultural identity and textile heritage of the region.",
    images: ["/rangwali.jpeg"],
    cloudinaryPublicIds: ["uttarakhand-heritage/products/rangwali-pichhoda-1"],
    rating: 4.7,
    reviewsCount: 67,
    culturalValue: "Traditional women's shawl representing Kumaon textile heritage",
    available: true,
    giCertified: true,
    giRegistrationNumber: "863",
    giRegistrationDate: "2023",
    artisan: {
      id: "pichhoda-artisan-1",
      name: "Kumaoni artisans",
      village: "Kumaon",
      district: "Almora",
      experience: "Traditional",
      specialization: "Shawl weaving",
      contact: "pichhoda@example.com",
      bio: "Traditional Kumaoni artisans preserving shawl weaving"
    },
    materials: "Wool, cotton, natural dyes",
    careInstructions: "Dry clean or gentle hand wash",
    tags: ["shawl", "textile", "traditional", "kumaon"],
    keywords: ["rangwali", "pichhoda", "shawl", "kumaon", "textile", "traditional"]
  },
  {
    name: "Chamoli Wooden Ramman Mask",
    category: "Handicraft",
    region: "Chamoli",
    description: "Wooden ritual masks for Ramman festival",
    longDescription: "Chamoli Wooden Ramman Masks are traditional wooden masks carved for the Ramman festival, a UNESCO Intangible Cultural Heritage. These masks are intricately carved and painted, representing various deities and characters from local mythology.",
    healthBenefits: ["Cultural preservation", "Artistic expression", "Traditional skill development"],
    culturalSignificance: "These masks are essential for the Ramman festival, a UNESCO-recognized cultural heritage. They represent the spiritual and cultural traditions of Chamoli and are used in religious ceremonies and performances.",
    images: ["/ramman.jpeg"],
    cloudinaryPublicIds: ["uttarakhand-heritage/products/ramman-mask-1"],
    rating: 4.8,
    reviewsCount: 43,
    culturalValue: "Ritual masks for UNESCO-recognized Ramman festival",
    available: true,
    giCertified: true,
    giRegistrationNumber: "864",
    giRegistrationDate: "2023",
    artisan: {
      id: "ramman-artisan-1",
      name: "Local wood carvers",
      village: "Chamoli",
      district: "Chamoli",
      experience: "Traditional",
      specialization: "Wooden mask carving",
      contact: "ramman@example.com",
      bio: "Traditional wood carvers creating Ramman festival masks"
    },
    materials: "Wood, natural paints, traditional tools",
    careInstructions: "Handle with care, store in dry place",
    tags: ["mask", "wood carving", "ritual", "cultural", "unesco"],
    keywords: ["ramman", "mask", "wooden", "chamoli", "festival", "unesco", "ritual"]
  },
  {
    name: "Uttarakhand Likhai (Wood Carving)",
    category: "Handicraft",
    region: "Kumaon region",
    description: "Traditional wood carving art with intricate designs",
    longDescription: "Uttarakhand Likhai is a traditional wood carving art form from the Kumaon region. This craft involves creating intricate designs and patterns on wood, used in architecture, furniture, and decorative items.",
    healthBenefits: ["Cultural preservation", "Artistic expression", "Traditional skill development"],
    culturalSignificance: "Likhai wood carving is an important traditional craft representing the artistic heritage of Kumaon. It's used in traditional architecture and decorative arts.",
    images: ["/likhai.jpeg"],
    cloudinaryPublicIds: ["uttarakhand-heritage/products/likhai-1"],
    rating: 4.6,
    reviewsCount: 59,
    culturalValue: "Traditional wood carving art representing Kumaon artistic heritage",
    available: true,
    giCertified: true,
    giRegistrationNumber: "865",
    giRegistrationDate: "2023",
    artisan: {
      id: "likhai-artisan-1",
      name: "Wood artisans",
      village: "Kumaon",
      district: "Almora",
      experience: "Traditional",
      specialization: "Wood carving",
      contact: "likhai@example.com",
      bio: "Traditional wood artisans preserving Likhai craft"
    },
    materials: "Wood, carving tools, natural finishes",
    careInstructions: "Dust regularly, avoid direct sunlight",
    tags: ["wood carving", "handicraft", "traditional", "artistic"],
    keywords: ["likhai", "wood carving", "kumaon", "traditional", "artistic"]
  },
  {
    name: "Uttarakhand Buransh Sharbat",
    category: "Agricultural",
    region: "Chamoli, Tehri",
    description: "Juice made from Rhododendron flowers",
    longDescription: "Uttarakhand Buransh Sharbat is a traditional beverage made from the flowers of Rhododendron arboreum (Buransh). This refreshing drink is known for its unique flavor and is a popular traditional beverage in the region.",
    healthBenefits: [
      "Rich in antioxidants",
      "Refreshing and hydrating",
      "Traditional medicinal properties",
      "Natural flavor"
    ],
    culturalSignificance: "Buransh Sharbat is a traditional beverage enjoyed in the region, especially during festivals. The Rhododendron flower holds cultural significance and is the state flower of Uttarakhand.",
    images: ["/buransh.webp"],
    cloudinaryPublicIds: ["uttarakhand-heritage/products/buransh-sharbat-1"],
    rating: 4.7,
    reviewsCount: 76,
    culturalValue: "Traditional beverage made from state flower",
    available: true,
    giCertified: true,
    giRegistrationNumber: "866",
    giRegistrationDate: "2023",
    artisan: {
      id: "buransh-artisan-1",
      name: "Local producers",
      village: "Chamoli",
      district: "Chamoli",
      experience: "Traditional",
      specialization: "Buransh sharbat production",
      contact: "buransh@example.com",
      bio: "Traditional producers of Buransh sharbat"
    },
    harvestSeason: "March - April",
    shelfLife: "12 months",
    storageInstructions: "Store in cool, dry place",
    tags: ["beverage", "sharbat", "rhododendron", "traditional"],
    keywords: ["buransh", "sharbat", "rhododendron", "beverage", "traditional", "chamoli"]
  },
  {
    name: "Nainital Mombatti (Candle)",
    category: "Handicraft",
    region: "Nainital",
    description: "Handmade decorative candles with traditional designs",
    longDescription: "Nainital Mombatti are handmade decorative candles created in Nainital. These candles are known for their beautiful designs, colors, and traditional craftsmanship, making them popular souvenirs and decorative items.",
    healthBenefits: ["Aesthetic value", "Cultural preservation", "Artistic expression"],
    culturalSignificance: "Candles from Nainital are an important part of the local handicraft industry. They're used in homes, hotels, and as decorative items, representing the artistic heritage of the region.",
    images: ["/mombatti.webp"],
    cloudinaryPublicIds: ["uttarakhand-heritage/products/mombatti-1"],
    rating: 4.5,
    reviewsCount: 41,
    culturalValue: "Handmade candles representing Nainital handicraft heritage",
    available: true,
    giCertified: true,
    giRegistrationNumber: "868",
    giRegistrationDate: "2023",
    artisan: {
      id: "mombatti-artisan-1",
      name: "Nainital candle makers",
      village: "Nainital",
      district: "Nainital",
      experience: "Traditional",
      specialization: "Candle making",
      contact: "mombatti@example.com",
      bio: "Traditional candle makers in Nainital"
    },
    materials: "Wax, wicks, dyes, decorative elements",
    careInstructions: "Store in cool place, handle with care",
    tags: ["candle", "handicraft", "decorative", "traditional"],
    keywords: ["mombatti", "candle", "nainital", "handicraft", "decorative"]
  }
]

